"""
Canonical book name mappings for ScriptureDepth.
Normalizes book names and abbreviations across OSIS XML, USFM, JSON, and TSV sources.
"""

BOOK_MAP = {
    # Old Testament
    "genesis": ("Genesis", "GEN", "OT", 50),
    "gen": ("Genesis", "GEN", "OT", 50),
    "ge": ("Genesis", "GEN", "OT", 50),
    "exodus": ("Exodus", "EXO", "OT", 40),
    "exo": ("Exodus", "EXO", "OT", 40),
    "ex": ("Exodus", "EXO", "OT", 40),
    "leviticus": ("Leviticus", "LEV", "OT", 27),
    "lev": ("Leviticus", "LEV", "OT", 27),
    "le": ("Leviticus", "LEV", "OT", 27),
    "numbers": ("Numbers", "NUM", "OT", 36),
    "num": ("Numbers", "NUM", "OT", 36),
    "nu": ("Numbers", "NUM", "OT", 36),
    "deuteronomy": ("Deuteronomy", "DEU", "OT", 34),
    "deu": ("Deuteronomy", "DEU", "OT", 34),
    "dt": ("Deuteronomy", "DEU", "OT", 34),
    "joshua": ("Joshua", "JOS", "OT", 24),
    "jos": ("Joshua", "JOS", "OT", 24),
    "judges": ("Judges", "JDG", "OT", 21),
    "jdg": ("Judges", "JDG", "OT", 21),
    "ruth": ("Ruth", "RUT", "OT", 4),
    "rut": ("Ruth", "RUT", "OT", 4),
    "ru": ("Ruth", "RUT", "OT", 4),
    "1 samuel": ("1 Samuel", "1SA", "OT", 31),
    "1sa": ("1 Samuel", "1SA", "OT", 31),
    "1 sam": ("1 Samuel", "1SA", "OT", 31),
    "2 samuel": ("2 Samuel", "2SA", "OT", 24),
    "2sa": ("2 Samuel", "2SA", "OT", 24),
    "2 sam": ("2 Samuel", "2SA", "OT", 24),
    "1 kings": ("1 Kings", "1KI", "OT", 22),
    "1ki": ("1 Kings", "1KI", "OT", 22),
    "2 kings": ("2 Kings", "2KI", "OT", 25),
    "2ki": ("2 Kings", "2KI", "OT", 25),
    "1 chronicles": ("1 Chronicles", "1CH", "OT", 29),
    "1ch": ("1 Chronicles", "1CH", "OT", 29),
    "2 chronicles": ("2 Chronicles", "2CH", "OT", 36),
    "2ch": ("2 Chronicles", "2CH", "OT", 36),
    "ezra": ("Ezra", "EZR", "OT", 10),
    "ezr": ("Ezra", "EZR", "OT", 10),
    "nehemiah": ("Nehemiah", "NEH", "OT", 13),
    "neh": ("Nehemiah", "NEH", "OT", 13),
    "esther": ("Esther", "EST", "OT", 10),
    "est": ("Esther", "EST", "OT", 10),
    "job": ("Job", "JOB", "OT", 42),
    "psalms": ("Psalms", "PSA", "OT", 150),
    "psalm": ("Psalms", "PSA", "OT", 150),
    "psa": ("Psalms", "PSA", "OT", 150),
    "ps": ("Psalms", "PSA", "OT", 150),
    "proverbs": ("Proverbs", "PRO", "OT", 31),
    "pro": ("Proverbs", "PRO", "OT", 31),
    "pr": ("Proverbs", "PRO", "OT", 31),
    "ecclesiastes": ("Ecclesiastes", "ECC", "OT", 12),
    "ecc": ("Ecclesiastes", "ECC", "OT", 12),
    "song of solomon": ("Song of Songs", "SNG", "OT", 8),
    "song of songs": ("Song of Songs", "SNG", "OT", 8),
    "sng": ("Song of Songs", "SNG", "OT", 8),
    "isaiah": ("Isaiah", "ISA", "OT", 66),
    "isa": ("Isaiah", "ISA", "OT", 66),
    "is": ("Isaiah", "ISA", "OT", 66),
    "jeremiah": ("Jeremiah", "JER", "OT", 52),
    "jer": ("Jeremiah", "JER", "OT", 52),
    "lamentations": ("Lamentations", "LAM", "OT", 5),
    "lam": ("Lamentations", "LAM", "OT", 5),
    "ezekiel": ("Ezekiel", "EZK", "OT", 48),
    "ezk": ("Ezekiel", "EZK", "OT", 48),
    "eze": ("Ezekiel", "EZK", "OT", 48),
    "daniel": ("Daniel", "DAN", "OT", 12),
    "dan": ("Daniel", "DAN", "OT", 12),
    "da": ("Daniel", "DAN", "OT", 12),
    "hosea": ("Hosea", "HOS", "OT", 14),
    "hos": ("Hosea", "HOS", "OT", 14),
    "joel": ("Joel", "JOL", "OT", 3),
    "jol": ("Joel", "JOL", "OT", 3),
    "joe": ("Joel", "JOL", "OT", 3),
    "amos": ("Amos", "AMO", "OT", 9),
    "amo": ("Amos", "AMO", "OT", 9),
    "obadiah": ("Obadiah", "OBA", "OT", 1),
    "oba": ("Obadiah", "OBA", "OT", 1),
    "jonah": ("Jonah", "JON", "OT", 4),
    "jon": ("Jonah", "JON", "OT", 4),
    "micah": ("Micah", "MIC", "OT", 7),
    "mic": ("Micah", "MIC", "OT", 7),
    "nahum": ("Nahum", "NAM", "OT", 3),
    "nam": ("Nahum", "NAM", "OT", 3),
    "nah": ("Nahum", "NAM", "OT", 3),
    "habakkuk": ("Habakkuk", "HAB", "OT", 3),
    "hab": ("Habakkuk", "HAB", "OT", 3),
    "zephaniah": ("Zephaniah", "ZEP", "OT", 3),
    "zep": ("Zephaniah", "ZEP", "OT", 3),
    "haggai": ("Haggai", "HAG", "OT", 2),
    "hag": ("Haggai", "HAG", "OT", 2),
    "zechariah": ("Zechariah", "ZEC", "OT", 14),
    "zec": ("Zechariah", "ZEC", "OT", 14),
    "malachi": ("Malachi", "MAL", "OT", 4),
    "mal": ("Malachi", "MAL", "OT", 4),

    # New Testament
    "matthew": ("Matthew", "MAT", "NT", 28),
    "mat": ("Matthew", "MAT", "NT", 28),
    "matt": ("Matthew", "MAT", "NT", 28),
    "mt": ("Matthew", "MAT", "NT", 28),
    "mark": ("Mark", "MRK", "NT", 16),
    "mrk": ("Mark", "MRK", "NT", 16),
    "mk": ("Mark", "MRK", "NT", 16),
    "luke": ("Luke", "LUK", "NT", 24),
    "luk": ("Luke", "LUK", "NT", 24),
    "lk": ("Luke", "LUK", "NT", 24),
    "john": ("John", "JHN", "NT", 21),
    "jhn": ("John", "JHN", "NT", 21),
    "jn": ("John", "JHN", "NT", 21),
    "acts": ("Acts", "ACT", "NT", 28),
    "act": ("Acts", "ACT", "NT", 28),
    "ac": ("Acts", "ACT", "NT", 28),
    "romans": ("Romans", "ROM", "NT", 16),
    "rom": ("Romans", "ROM", "NT", 16),
    "ro": ("Romans", "ROM", "NT", 16),
    "1 corinthians": ("1 Corinthians", "1CO", "NT", 16),
    "1co": ("1 Corinthians", "1CO", "NT", 16),
    "1 cor": ("1 Corinthians", "1CO", "NT", 16),
    "2 corinthians": ("2 Corinthians", "2CO", "NT", 13),
    "2co": ("2 Corinthians", "2CO", "NT", 13),
    "2 cor": ("2 Corinthians", "2CO", "NT", 13),
    "galatians": ("Galatians", "GAL", "NT", 6),
    "gal": ("Galatians", "GAL", "NT", 6),
    "ga": ("Galatians", "GAL", "NT", 6),
    "ephesians": ("Ephesians", "EPH", "NT", 6),
    "eph": ("Ephesians", "EPH", "NT", 6),
    "philippians": ("Philippians", "PHP", "NT", 4),
    "php": ("Philippians", "PHP", "NT", 4),
    "phil": ("Philippians", "PHP", "NT", 4),
    "colossians": ("Colossians", "COL", "NT", 4),
    "col": ("Colossians", "COL", "NT", 4),
    "1 thessalonians": ("1 Thessalonians", "1TH", "NT", 5),
    "i thessalonians": ("1 Thessalonians", "1TH", "NT", 5),
    "1th": ("1 Thessalonians", "1TH", "NT", 5),
    "1 thess": ("1 Thessalonians", "1TH", "NT", 5),
    "2 thessalonians": ("2 Thessalonians", "2TH", "NT", 3),
    "ii thessalonians": ("2 Thessalonians", "2TH", "NT", 3),
    "2th": ("2 Thessalonians", "2TH", "NT", 3),
    "2 thess": ("2 Thessalonians", "2TH", "NT", 3),
    "1 timothy": ("1 Timothy", "1TI", "NT", 6),
    "1ti": ("1 Timothy", "1TI", "NT", 6),
    "1 tim": ("1 Timothy", "1TI", "NT", 6),
    "2 timothy": ("2 Timothy", "2TI", "NT", 4),
    "2ti": ("2 Timothy", "2TI", "NT", 4),
    "2 tim": ("2 Timothy", "2TI", "NT", 4),
    "titus": ("Titus", "TIT", "NT", 3),
    "tit": ("Titus", "TIT", "NT", 3),
    "philemon": ("Philemon", "PHM", "NT", 1),
    "phm": ("Philemon", "PHM", "NT", 1),
    "phlm": ("Philemon", "PHM", "NT", 1),
    "hebrews": ("Hebrews", "HEB", "NT", 13),
    "heb": ("Hebrews", "HEB", "NT", 13),
    "james": ("James", "JAS", "NT", 5),
    "jas": ("James", "JAS", "NT", 5),
    "jas.": ("James", "JAS", "NT", 5),
    "jm": ("James", "JAS", "NT", 5),
    "1 peter": ("1 Peter", "1PE", "NT", 5),
    "1pe": ("1 Peter", "1PE", "NT", 5),
    "1 pet": ("1 Peter", "1PE", "NT", 5),
    "2 peter": ("2 Peter", "2PE", "NT", 3),
    "2pe": ("2 Peter", "2PE", "NT", 3),
    "2 pet": ("2 Peter", "2PE", "NT", 3),
    "1 john": ("1 John", "1JN", "NT", 5),
    "1jn": ("1 John", "1JN", "NT", 5),
    "2 john": ("2 John", "2JN", "NT", 1),
    "2jn": ("2 John", "2JN", "NT", 1),
    "3 john": ("3 John", "3JN", "NT", 1),
    "3jn": ("3 John", "3JN", "NT", 1),
    "jude": ("Jude", "JUD", "NT", 1),
    "jud": ("Jude", "JUD", "NT", 1),
    "jd": ("Jude", "JUD", "NT", 1),
    "revelation": ("Revelation", "REV", "NT", 22),
    "rev": ("Revelation", "REV", "NT", 22),
    "re": ("Revelation", "REV", "NT", 22),
}


def normalize_book(raw_name: str):
    """
    Normalizes a book string (e.g. 'Gen', '1 John', 'JHN')
    Returns: (canonical_name, book_code, testament, total_chapters)
    """
    cleaned = raw_name.strip().lower()
    return BOOK_MAP.get(cleaned, (raw_name.strip(), raw_name.strip().upper()[:3], "OT", 1))
